version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: academy-portal-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  # Server service
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    container_name: academy-portal-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/academy_portal?authSource=admin
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./packages/server:/app
      - /app/node_modules

  # Web service
  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    container_name: academy-portal-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  # Mobile service (development)
  mobile:
    build:
      context: ./packages/mobile
      dockerfile: Dockerfile
    container_name: academy-portal-mobile
    restart: always
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - server
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost

volumes:
  mongodb_data: 